import type { RBACConfig } from "./types";

// ─── Schema Generators ────────────────────────────────────────────────────────
// These return strings you can write to generated migration/schema files.

/** PostgreSQL migration snippet for adding a role column to a users table */
export function generatePostgresRoleMigration(config: RBACConfig): string {
  const roleValues = config.roles.map((r) => `'${r.key}'`).join(", ");
  return `
-- Auto-generated by PostPipe RBAC preset
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM (${roleValues});
EXCEPTION WHEN duplicate_object THEN null;
END $$;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS role user_role NOT NULL DEFAULT '${config.defaultRole}';

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
`.trim();
}

/** MongoDB schema snippet (Mongoose) */
export function generateMongooseUserSchema(config: RBACConfig): string {
  const roleValues = config.roles.map((r) => `"${r.key}"`).join(", ");
  return `
// Auto-generated by PostPipe RBAC preset
import mongoose from "mongoose";

const UserSchema = new mongoose.Schema({
  email: { type: String, required: true, unique: true },
  role: {
    type: String,
    enum: [${roleValues}],
    default: "${config.defaultRole}",
  },
  createdAt: { type: Date, default: Date.now },
});

export const User = mongoose.models.User ?? mongoose.model("User", UserSchema);
`.trim();
}

/** Prisma schema snippet */
export function generatePrismaRoleEnum(config: RBACConfig): string {
  const roleValues = config.roles.map((r) => `  ${r.key.toUpperCase()}`).join("\n");
  return `
// Auto-generated by PostPipe RBAC preset
enum Role {
${roleValues}
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  role      Role     @default(${config.defaultRole.toUpperCase()})
  createdAt DateTime @default(now())
}
`.trim();
}